// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgWeq84MFufYRHFuH3oiBjtmbScB5nft8',
    appId: '1:1053282621473:web:323a0789424c2f4cf92b60',
    messagingSenderId: '1053282621473',
    projectId: 'studio-9401559078-23caf',
    authDomain: 'studio-9401559078-23caf.firebaseapp.com',
    databaseURL: 'https://studio-9401559078-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'studio-9401559078-23caf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUT2R0bFQwBg-k9JMmUggcMZCdOa1vWZc',
    appId: '1:1053282621473:android:4e5555bc6cd88e24f92b60',
    messagingSenderId: '1053282621473',
    projectId: 'studio-9401559078-23caf',
    databaseURL: 'https://studio-9401559078-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'studio-9401559078-23caf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFauXg1X9HPZSkuTHJMEhCrAgPZlkx0nY',
    appId: '1:1053282621473:ios:43f32a9cc0db3b4ff92b60',
    messagingSenderId: '1053282621473',
    projectId: 'studio-9401559078-23caf',
    databaseURL: 'https://studio-9401559078-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'studio-9401559078-23caf.firebasestorage.app',
    androidClientId: '1053282621473-nfqm8rrgve0nttcc181c1mq3p1mh2fod.apps.googleusercontent.com',
    iosClientId: '1053282621473-943f88031jjfrefvm9msuouvlggsol68.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradequest',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFauXg1X9HPZSkuTHJMEhCrAgPZlkx0nY',
    appId: '1:1053282621473:ios:43f32a9cc0db3b4ff92b60',
    messagingSenderId: '1053282621473',
    projectId: 'studio-9401559078-23caf',
    databaseURL: 'https://studio-9401559078-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'studio-9401559078-23caf.firebasestorage.app',
    androidClientId: '1053282621473-nfqm8rrgve0nttcc181c1mq3p1mh2fod.apps.googleusercontent.com',
    iosClientId: '1053282621473-943f88031jjfrefvm9msuouvlggsol68.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgWeq84MFufYRHFuH3oiBjtmbScB5nft8',
    appId: '1:1053282621473:web:323a0789424c2f4cf92b60',
    messagingSenderId: '1053282621473',
    projectId: 'studio-9401559078-23caf',
    authDomain: 'studio-9401559078-23caf.firebaseapp.com',
    databaseURL: 'https://studio-9401559078-23caf-default-rtdb.firebaseio.com',
    storageBucket: 'studio-9401559078-23caf.firebasestorage.app',
  );
}
